name: stress-ng-dev
base: core24
adopt-info: version
summary: stress-ng will stress test a computer system in various selectable ways
description: |
  This snap is intended for use only on Ubuntu Core systems.
  For other Ubuntu installations, such as server or desktop, the recommended option is to use the Debian package.

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

grade: stable
confinement: devmode

parts:
  version:
    source: .
    plugin: nil
    build-packages:
      - jq
      - curl
      - git
    override-build: |
      craftctl default
      craftctl set version=$(curl -s https://api.github.com/repos/ColinIanKing/stress-ng/tags | jq -r '.[0].name')+$(git rev-parse --short HEAD)

  stress-ng:
    source: https://github.com/ColinIanKing/stress-ng.git
    plugin: make
    make-parameters: ["-j$(nproc)"]
    build-packages:
      - build-essential
      - make
      - git
      - jq
    override-pull: |
      craftctl default
      git checkout $(curl -s https://api.github.com/repos/ColinIanKing/stress-ng/tags | jq -r '.[0].name')

apps:
  stress-ng:
    command: usr/bin/stress-ng
