#!/bin/bash -e

# Verify if SNAP_SAVE_DATA is unset, indicating the system is not Ubuntu Core
# see: https://snapcraft.io/docs/environment-variables#heading--snap-save-data
if [ -z "${SNAP_SAVE_DATA}" ]; then
  echo -e "Error: detected non-Ubuntu Core system."
  echo -e "This snap is meant for Ubuntu Core (https://ubuntu.com/core) only."
  echo -e "\nRefer to the project documentation for other installation methods: https://github.com/ColinIanKing/stress-ng/blob/master/README.md"
  exit 1
fi
